version: '3.8'

services:
 web:
  build:
   context: /app
  ports:
  - 443:5000
  volumes:
  - ./:/app
  - /etc/letsencrypt:/etc/letsencrypt
  depends_on:
   - mysqldb

 mysqldb:
  image: mysql
  ports:
  - 3306:3306
  environment:
  - MYSQL_ROOT_PASSWORD=samuel1234
  volumes:
  - mysql_jogoteca:/var/lib/mysql
  - mysql_jogoteca_config:/etc/mysql

volumes:
  mysql_jogoteca:
  mysql_jogoteca_config: